project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - artist-datamodel.qmd
    - exhibition-datamodel.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb
  metadata:
    - name: "Rahaf Raad"
      orcid: "0009-0002-4461-8235"
      
website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: artist-datamodel.qmd
        text: Künstler-Datamodel
      - href: exhibition-datamodel.qmd
        text: Ausstellung-Datamodel
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
